name: Run tests on PR to main

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, repoened]
    paths-ignore:
      - '**/*.md'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    
    - name: Restore dependencies
      run: dotnet restore GlobalP.Elevator/GlobalP.Elevator.sln

    - name: Build
      run: dotnet build GlobalP.Elevator/GlobalP.Elevator.sln --no-restore --configuration Release

    - name: Run tests with coverage
      run: dotnet test GlobalP.Elevator/GlobalP.Elevator.sln --no-build --configuration Release --collect:"XPlat Code Coverage"

    - name: Report coverage
      uses: danielpalme/ReportGenerator-Github-Action@5.1.26
      with:
        reports: '**/coverage.cobertura.xml'
        targetdir: 'coveragereport'
        reporttypes: 'HtmlInline;Cobertura'

    - name: Upload coverage report artifact
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coveragereport
